### PR TITLE
Fix upgrade zipkin2

### LINKED ISSUE #57: SOFATracer remote report data to Zipkin version 2.1.X version problem
### Describe the bug

* 1.TraceId we print to disk and report to Zipkin length are not equal.Such as print disk is  `0a0fe87a153519650379710017813` ，but in Zipkin 

image

* 2.SpanId and parentSpanId error. The parentSpanId in  Zipkin version 2.1.X report is blank ,

image

If no parentSpanId the SOFATracer Link path will hava no layer.

### Expected behavior

TraceId should be same and  Zipkin view has the SOFATracer link path layer.

### Actual behavior

TraceId not same and parentSpanId error.

### Steps to reproduce

[Can use such example](https://github.com/guanchao-yang/sofa-tracer-demo)

### PR DESCRIPTION
**Pull request by glmapper**
### Motivation:

1、resolve parentSpanId in Zipkin version 2.1.X report is blank .
2、adapter SOFARpc span to zipkin span 
3、upgrade zipkin version to 2.11.3 

### Result:

Fixes #57 . 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

File: tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/zipkin/ZipkinSofaTracerSpanRemoteReporter.java [hunk 1]
```diff
@@ -110,37 +109,36 @@ private Span convertToZipkinSpan(SofaTracerSpan sofaTracerSpan) {
...
-
         }
 
         //spanId
         String spanId = sofaTracerSpanContext.getSpanId();
         zipkinSpanBuilder.id(spanIdToLong(spanId));
+        //kind
+        SofaTracer sofaTracer = sofaTracerSpan.getSofaTracer();
+        // adapter SOFARpc span model
+        if ("RPC_TRACER".equals(sofaTracer.getTracerType())) {
```
Comment (ujjboy) [inline tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/zipkin/ZipkinSofaTracerSpanRemoteReporter.java]: Magic value.  `"RPC_TRACER"`
